### ISSUE TITLE
运行FaceRank-master/run_model.py的方法，报错了，model的文件从百度下载放进去了

### ISSUE THREAD

**Issue by ithjz** [fendouai/FaceRank#4]
E:\ProgramData\Anaconda3\python.exe D:/360c/FaceRank-master/run_model.py
(?, 128, 128, 24)
(?, 64, 64, 24)
(?, 64, 64, 96)
(?, 32, 32, 96)
2017-09-08 10:56:33.912298: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-08 10:56:33.912298: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "D:/360c/FaceRank-master/run_model.py", line 144, in <module>
    pred_result_test=sess.run(pred_result, feed_dict={x: batch_xs,keep_prob: 1.})
[]
  File "E:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
0
    run_metadata_ptr)
(0,)
  File "E:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'Placeholder:0', which has shape '(?, 128, 128, 3)'

Process finished with exit code 1

**Comment by fendouai** [comment]
model 放好了，直接运行 run_model

**Comment by ithjz** [comment]
model放好了 ，直接运行 run_model ，出现错误

E:\ProgramData\Anaconda3\python.exe D:/360c/FaceRank-master/run_model.py
(?, 128, 128, 24)
(?, 64, 64, 24)
(?, 64, 64, 96)
(?, 32, 32, 96)
2017-09-08 15:22:00.272525: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-08 15:22:00.272525: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
[]
Traceback (most recent call last):
0
  File "D:/360c/FaceRank-master/run_model.py", line 144, in <module>
(0,)
    pred_result_test=sess.run(pred_result, feed_dict={x: batch_xs,keep_prob: 1.})
  File "E:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "E:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'Placeholder:0', which has shape '(?, 128, 128, 3)'

Process finished with exit code 1

**Comment by lz2004xxw** [comment]
我是这个错误

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader c
onstructor: Failed to get matching files on ./model/model.ckpt: Not found: FindF
irstFile failed for: ./model : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\ud
cc4·\udcbe\udcb6\udca1\udca3
; No such process
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT
, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _d
evice="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/
RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by fendouai** [comment]
没有在 windows 上测试过，目前有这个问题的都是 windows 系统的，建议试一下 Ubuntu。

**Comment by idreamsoft** [comment]
@ithjz 能共享下model 吗
